name: CI/CD Kotlin Multiplatform con TMDb

on:
  push:
    branches:
      - main
      - developer
      - 'feature-*'
  pull_request:
    branches:
      - developer
      - main

jobs:
  build:
    name: 🔨 Compilar y Testear
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout del código
        uses: actions/checkout@v4  # 🔹 ACTUALIZADO a @v4

      - name: ☕ Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🔧 Configurar Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: 🔑 Dar permisos de ejecución a gradlew
        run: chmod +x gradlew  # 🔹 SOLUCIÓN AL ERROR `Permission denied`

      - name: 📦 Descargar dependencias
        run: ./gradlew dependencies

      - name: ✅ Compilar módulo Android
        run: ./gradlew assembleDebug

      - name: ✅ Compilar módulo KMM
        run: ./gradlew compileKotlinMetadata

      - name: 🧪 Ejecutar pruebas unitarias
        run: ./gradlew testDebugUnit
